apiVersion: v1
kind: LimitRange
metadata:
  name: limitrange
  namespace: magedu
spec:
  limits:
  - type: Container
    max:
      cpu: "1"      #限制单个容器的最大cpu
      memory: "500Mi"
    min:        
      cpu: "200m"   #限制单个容器的最小cpu
      memory: "128Mi"
    default:        #默认单个容器的cpu限制
      cpu: "400m"
      memory: "256Mi"
    defaultRequest: #默认单个容器的cpu创建请求
      cpu: "256m"
      memory: "256Mi"
    maxLimitRequestRatio:
      cpu: 2       #限制cpu limit/request比值最大为2
      memory: "256Mi"
  - type: Pod
    max:
      cpu: "1"
      memory: "1Gi"
  - type: PersistentVolumeClaim
    max:
      storage: 50Gi  #限制pvc的最大requests.storage
    min:
      storage: 30Gi  #限制pvc最小
